Repository foggie-sims/enzo-foggie, pull requests merged in 2023-10, with the labels that each got.

#2 just a test
  halloween-prank
Labels: enhancement, good first issue

#1 JT branch - comments added to Grid_CollectGridInformation
  src/enzo/Grid_CollectGridInformation.C
Labels: good first issue

#3 a Third comment in C_CGI
  src/enzo/Grid_CollectGridInformation.C
Labels: documentation
